import Link from "next/link";
import { ArrowRight, Building2, CalendarCheck, Check, Clock3, Heart, MapPin, MessageCircle, MessagesSquare, Plane, Route, Sparkles, TrainFront, Utensils, Users, Volume2 } from "lucide-react";
import { SiteShell } from "@/components/site-shell";
import { ContactActions } from "@/components/contact-actions";
import { ReservationForm } from "@/components/forms";
import { activeServices, business, phoneHref, whatsappHref } from "@/lib/business-config";

const icons=[Clock3,CalendarCheck,TrainFront,Plane,Building2,Utensils,Users,MapPin,Route];
export default function Home(){return <SiteShell>
 <section className="hero hero-taxi"><div className="hero-pattern"/><div className="hero-content"><span className="hero-label"><MapPin/>Jouw taxi in Roermond en omgeving</span><p className="hero-brand">Bada Bing Taxi</p><h1>Jouw rit.<br/><em>Jouw sfeer.</em></h1><p className="hero-lead">Gezellig kletsen of liever rustig achterover? Jij bepaalt. Wij brengen je persoonlijk, comfortabel en zonder gedoe.</p><ContactActions inverse/><div className="trust-points"><span><Check/>Direct persoonlijk contact</span><span><Check/>06 24 93 19 77</span><span><Check/>Duidelijke afspraken</span></div></div><div className="hero-car-label"><span>Onze stijl</span><b>Bronsgroen. Comfortabel. Herkenbaar.</b></div></section>
 <section className="booking-band"><ReservationForm compact/></section>
 <section className="section personal-ride"><div className="personal-copy"><span className="kicker">Meer dan alleen vervoer</span><h2>Een rit die bij jouw moment past.</h2><p>Vroeg naar het station, met koffers naar het vliegveld of na een lange avond veilig naar huis. Bij Bada Bing hoef je niet uit te leggen hoe een taxirit hoort te voelen. Jij geeft aan waar je behoefte aan hebt.</p><Link className="text-link" href="/over-ons">Maak kennis met Bada Bing <ArrowRight/></Link></div><div className="mood-cards"><article><MessagesSquare/><span>Praatmodus</span><h3>Gezellig kletsen</h3><p>Zin in een praatje? Leuk. We maken er onderweg een fijne rit van.</p></article><article><Volume2/><span>Rustmodus</span><h3>Lekker in stilte</h3><p>Even niets hoeven. Achterover, muziek zacht en rustig naar je bestemming.</p></article><article><Heart/><span>Altijd</span><h3>Persoonlijke aandacht</h3><p>Van ophaalplek tot bestemming denken we met je mee.</p></article></div></section>
 <section className="section why"><div className="section-head"><span className="kicker">Waarom Bada Bing Taxi</span><h2>Instappen zonder gedoe.</h2><p>Persoonlijk contact en heldere afspraken voor ritten in Roermond en daarbuiten.</p></div><div className="benefit-grid">{[[Sparkles,"Snel geregeld","Bel of app direct. Voor later reserveren kan ook."],[MessageCircle,"Persoonlijk contact","Je spreekt rechtstreeks af wat je nodig hebt."],[MapPin,"Lokale kennis","Bekend in Roermond en de omliggende plaatsen."],[CalendarCheck,"Duidelijke afspraken","Je weet waar en wanneer je wordt opgehaald."]].map(([Icon,title,text])=><article key={title as string}><Icon/><h3>{title as string}</h3><p>{text as string}</p></article>)}</div></section>
 <section className="section services-home"><div className="section-head split"><div><span className="kicker">Waar kunnen we je brengen?</span><h2>Een taxi voor elk moment.</h2></div><Link className="text-link" href="/diensten">Bekijk alle diensten <ArrowRight/></Link></div><div className="service-grid">{activeServices.slice(0,6).map((s,i)=>{const Icon=icons[i];return <Link href={`/diensten/${s.slug}`} className="service-card" key={s.slug}><Icon/><span>0{i+1}</span><h3>{s.title}</h3><p>{s.short}</p><b>Meer over deze dienst <ArrowRight/></b></Link>})}</div></section>
 <section className="how"><div className="section"><span className="kicker light">Zo werkt het</span><h2>Drie stappen. Taxi geregeld.</h2><ol><li><b>1</b><div><h3>Bel, app of reserveer</h3><p>Vertel waar je bent en waar je heen wilt.</p></div></li><li><b>2</b><div><h3>Ontvang bevestiging</h3><p>We spreken tijd, plek en eventuele prijsindicatie af.</p></div></li><li><b>3</b><div><h3>Stap ontspannen in</h3><p>Sta klaar op de afgesproken ophaalplek.</p></div></li></ol></div></section>
 <section className="section routes"><div className="section-head"><span className="kicker">Veelgevraagde bestemmingen</span><h2>Van Roermond naar waar jij moet zijn.</h2></div><div className="route-list">{["Roermond Centraal","Designer Outlet Roermond","Binnenstad Roermond","Ziekenhuis","Hotels en restaurants","Vliegvelden"].map(x=><div key={x}><MapPin/><span>{x}</span><a href={whatsappHref(`Hallo Bada Bing Taxi, ik wil graag een prijs aanvragen voor een rit naar ${x}.`)}>Vraag een prijs aan</a></div>)}</div></section>
 <section className="section price-panel"><div><span className="kicker">Tarieven</span><h2>Vooraf weten waar je aan toe bent?</h2><p>De actuele tarieven zijn nog niet ingevuld. Vraag vrijblijvend een prijsindicatie aan voor jouw rit.</p></div><div className="price-actions"><a className="btn btn-yellow" href={phoneHref}>Bel voor een prijs</a><a className="btn btn-whatsapp" href={whatsappHref("Hallo Bada Bing Taxi, ik wil graag een prijsindicatie aanvragen.")}>Vraag via WhatsApp</a></div></section>
 <section className="area-section"><div className="section area-grid"><div><span className="kicker light">Werkgebied</span><h2>Thuis in Roermond en de regio.</h2><p>We behandelen aanvragen vanuit de geactiveerde plaatsen hieronder. Een andere vertrekplaats? Neem even contact op.</p><Link href="/werkgebied" className="btn btn-white">Bekijk het werkgebied</Link></div><div className="area-cloud">{business.areas.map((a,i)=><span className={i===0?"active":""} key={a}>{a}</span>)}</div></div></section>
 <section className="section business-block"><div className="business-icon"><Building2/></div><div><span className="kicker">Zakelijk vervoer</span><h2>Gastvrij vervoer voor je bedrijf.</h2><p>Voor bedrijven, hotels, restaurants, evenementenlocaties en terugkerende ritten. Facturatie kan na een persoonlijke afspraak.</p></div><Link className="btn btn-blue" href="/zakelijk-vervoer">Bespreek zakelijk vervoer</Link></section>
 <section className="final-cta"><div><span className="kicker light">Eén belletje. Eén appje.</span><h2>Waar je ook heen moet:<br/>Bada Bing, geregeld.</h2><ContactActions inverse/></div></section>
 </SiteShell>}
