"use client";
import { FormEvent, useState } from "react";
import { CheckCircle2, MessageCircle, Send } from "lucide-react";
import { business, whatsappHref } from "@/lib/business-config";

type Status = { kind: "idle" | "loading" | "success" | "demo" | "error"; message?: string; summary?: string };
const FieldError = ({ id, text }: { id: string; text?: string }) => text ? <span id={id} className="field-error">{text}</span> : null;

export function ReservationForm({ compact = false }: { compact?: boolean }) {
 const [status, setStatus] = useState<Status>({ kind: "idle" }); const [errors, setErrors] = useState<Record<string,string>>({}); const [wa, setWa] = useState(whatsappHref());
 async function submit(e: FormEvent<HTMLFormElement>) { e.preventDefault(); if(status.kind === "loading") return; const form=e.currentTarget; const data=Object.fromEntries(new FormData(form)); const next:Record<string,string>={}; for(const key of ["pickup","destination","date","time","passengers","name","phone","privacy"]) if(!data[key]) next[key]="Vul dit veld in."; setErrors(next); if(Object.keys(next).length) return; setStatus({kind:"loading"}); const message=`Hallo Bada Bing Taxi, ik wil graag een taxi aanvragen van ${data.pickup} naar ${data.destination} op ${data.date} om ${data.time}.`; setWa(whatsappHref(message)); try { const res=await fetch("/api/reservation",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)}); const json=await res.json(); if(json.demo){const subject=encodeURIComponent(`Ritaanvraag ${data.pickup} → ${data.destination}`);const body=encodeURIComponent(`Naam: ${data.name}\nTelefoon: ${data.phone}\nVan: ${data.pickup}\nNaar: ${data.destination}\nDatum: ${data.date}\nTijd: ${data.time}\nPassagiers: ${data.passengers}\nBijzonderheden: ${data.notes||"Geen"}`);window.location.href=`mailto:${business.email}?subject=${subject}&body=${body}`;} setStatus({kind:res.ok?"success":json.demo?"demo":"error",message:json.demo?`Je e-mailprogramma is geopend met de aanvraag voor ${business.email}. Verstuur de e-mail om te reserveren.`:json.message,summary:`${data.pickup} → ${data.destination} · ${data.date} om ${data.time}`}); if(res.ok) form.reset(); } catch { setStatus({kind:"error",message:"Verzenden lukt nu niet. Bel of stuur ons een WhatsApp."}); } }
 return <form className={`form-card ${compact?"compact":""}`} onSubmit={submit} noValidate><div className="form-intro"><span className="kicker">Ritaanvraag</span><h2>{compact?"Snel reserveren":"Vraag je rit aan"}</h2><p>Je aanvraag is pas definitief na een persoonlijke bevestiging.</p></div><div className="form-grid">
  <label>Ophaallocatie<input name="pickup" autoComplete="street-address" aria-describedby="pickup-error" placeholder="Straat, plaats of herkenningspunt"/><FieldError id="pickup-error" text={errors.pickup}/></label>
  <label>Bestemming<input name="destination" placeholder="Waar wil je heen?" aria-describedby="destination-error"/><FieldError id="destination-error" text={errors.destination}/></label>
  <label>Datum<input name="date" type="date" min={new Date().toISOString().split("T")[0]} aria-describedby="date-error"/><FieldError id="date-error" text={errors.date}/></label>
  <label>Tijd<input name="time" type="time" aria-describedby="time-error"/><FieldError id="time-error" text={errors.time}/></label>
  <label>Aantal passagiers<select name="passengers" defaultValue="" aria-describedby="passengers-error"><option value="" disabled>Kies aantal</option>{[1,2,3,4].map(n=><option key={n}>{n}</option>)}</select><FieldError id="passengers-error" text={errors.passengers}/></label>
  <label>Naam<input name="name" autoComplete="name" aria-describedby="name-error"/><FieldError id="name-error" text={errors.name}/></label>
  <label>Telefoonnummer<input name="phone" type="tel" autoComplete="tel" inputMode="tel" aria-describedby="phone-error"/><FieldError id="phone-error" text={errors.phone}/></label>
  <label className="wide">Bijzonderheden <span>(optioneel)</span><textarea name="notes" rows={3} maxLength={500} placeholder="Bijvoorbeeld bagage of een tussenstop"/></label><input className="honeypot" name="website" tabIndex={-1} autoComplete="off" aria-hidden="true"/>
  <label className="check wide"><input name="privacy" type="checkbox" value="accepted"/><span>Ik ga akkoord met de <a href="/privacyverklaring">privacyvoorwaarden</a> voor deze aanvraag.</span></label>
 </div><button className="btn btn-blue submit" disabled={status.kind==="loading"}><Send />{status.kind==="loading"?"Bezig…":"Vraag mijn rit aan"}</button>{status.kind!=="idle"&&status.kind!=="loading"&&<div className={`form-status ${status.kind}`} role="status"><CheckCircle2/><div><strong>{status.kind==="success"?"Aanvraag ontvangen":status.kind==="demo"?"Nog niet verzonden":"Verzenden niet gelukt"}</strong><p>{status.message}</p>{status.summary&&<p className="summary">{status.summary}</p>}<a className="btn btn-whatsapp" href={wa}><MessageCircle/>Ga verder via WhatsApp</a></div></div>}</form>
}

export function ContactForm(){const [status,setStatus]=useState<Status>({kind:"idle"}); async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget;const data=Object.fromEntries(new FormData(form));setStatus({kind:"loading"});try{const res=await fetch("/api/contact",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(data)});const json=await res.json();setStatus({kind:res.ok?"success":json.demo?"demo":"error",message:json.message});if(res.ok)form.reset()}catch{setStatus({kind:"error",message:"Verzenden lukt nu niet. Probeer bellen of WhatsApp."})}} return <form className="form-card" onSubmit={submit}><h2>Stuur een bericht</h2><div className="form-grid"><label>Naam<input name="name" required autoComplete="name"/></label><label>Telefoonnummer<input name="phone" type="tel" required autoComplete="tel"/></label><label className="wide">E-mailadres <span>(optioneel)</span><input name="email" type="email" autoComplete="email"/></label><label className="wide">Bericht<textarea name="message" required rows={5} maxLength={1000}/></label><input className="honeypot" name="website" tabIndex={-1} aria-hidden="true"/><label className="check wide"><input name="privacy" type="checkbox" required value="accepted"/><span>Ik ga akkoord met de <a href="/privacyverklaring">privacyvoorwaarden</a>.</span></label></div><button className="btn btn-blue submit" disabled={status.kind==="loading"}><Send/>Verstuur bericht</button>{status.kind!=="idle"&&<p className={`simple-status ${status.kind}`} role="status">{status.message}</p>}</form>}
