"use client";
import Link from "next/link";
import { Menu, Phone, X, MessageCircle, CalendarDays } from "lucide-react";
import { useEffect, useState } from "react";
import { business, phoneHref, whatsappHref } from "@/lib/business-config";
import { Logo } from "@/components/logo";

const nav = [["Diensten", "/diensten"], ["Tarieven", "/tarieven"], ["Werkgebied", "/werkgebied"], ["Over ons", "/over-ons"], ["Contact", "/contact"]];
export function Header() {
  const [open, setOpen] = useState(false); const [scrolled,setScrolled]=useState(false); const [hidden,setHidden]=useState(false);
  useEffect(()=>{let last=window.scrollY;const move=()=>{const y=window.scrollY;setScrolled(y>20);setHidden(y>last&&y>180&&!open);last=y};window.addEventListener("scroll",move,{passive:true});return()=>window.removeEventListener("scroll",move)},[open]);
  return <header className={`header ${scrolled?"header-scrolled":""} ${hidden?"header-hidden":""}`}><div className="header-inner"><Logo /><nav className="animated-nav" aria-label="Hoofdnavigatie">{nav.map(([label, href]) => <Link key={href} href={href}><span>{label}</span></Link>)}</nav><a className="header-phone" href={phoneHref}><Phone/>06 24 93 19 77</a><Link className="btn btn-yellow desktop-order" href="/reserveren">Reserveer</Link><button className="menu-button" onClick={() => setOpen(!open)} aria-expanded={open} aria-controls="mobile-menu" aria-label={open ? "Menu sluiten" : "Menu openen"}>{open ? <X /> : <Menu />}</button></div>{open && <nav id="mobile-menu" className="mobile-menu" aria-label="Mobiele navigatie">{nav.map(([label, href]) => <Link key={href} href={href} onClick={() => setOpen(false)}>{label}</Link>)}<a href={phoneHref}><Phone/> Bel 06 24 93 19 77</a><a href={whatsappHref()}><MessageCircle/> WhatsApp ons</a><Link className="btn btn-yellow" href="/reserveren">Taxi bestellen</Link></nav>}</header>;
}
export function MobileBar() { return <nav className="mobile-action" aria-label="Snel contact"><a href={phoneHref}><Phone /><span>Bel nu</span></a><a href={whatsappHref()}><MessageCircle /><span>WhatsApp</span></a><Link href="/reserveren"><CalendarDays /><span>Reserveer</span></Link></nav>; }
export function Footer() { const year = new Date().getFullYear(); return <footer className="footer"><div className="footer-grid"><div><Logo light /><p className="footer-tag">{business.tagline}</p>{(!business.phone || !business.email) && <p className="config-note">Contactgegevens worden nog aangeleverd.</p>}</div><div><h2>Contact</h2>{business.phone && <a href={phoneHref}>{business.phone}</a>}{business.email && <a href={`mailto:${business.email}`}>{business.email}</a>}{business.address && <p>{business.address}</p>}<Link href="/contact">Contact opnemen</Link></div><div><h2>Ga naar</h2><Link href="/taxi-roermond">Taxi Roermond</Link><Link href="/diensten">Diensten</Link><Link href="/werkgebied">Werkgebied</Link><Link href="/veelgestelde-vragen">Veelgestelde vragen</Link></div><div><h2>Juridisch</h2><Link href="/privacyverklaring">Privacyverklaring</Link><Link href="/cookiebeleid">Cookiebeleid</Link><Link href="/algemene-voorwaarden">Algemene voorwaarden</Link><Link href="/toegankelijkheidsverklaring">Toegankelijkheid</Link></div></div><div className="footer-bottom"><span>© {year} {business.name}</span><span>{[business.kvk && `KVK ${business.kvk}`, business.vat && `BTW ${business.vat}`].filter(Boolean).join(" · ")}</span></div></footer>; }
export function SiteShell({ children }: { children: React.ReactNode }) { return <><a className="skip" href="#inhoud">Ga naar inhoud</a><Header /><main id="inhoud">{children}</main><Footer /><MobileBar /></>; }
